// Generated by gencpp from file sensor_actuator/LightRequest.msg
// DO NOT EDIT!


#ifndef SENSOR_ACTUATOR_MESSAGE_LIGHTREQUEST_H
#define SENSOR_ACTUATOR_MESSAGE_LIGHTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_actuator
{
template <class ContainerAllocator>
struct LightRequest_
{
  typedef LightRequest_<ContainerAllocator> Type;

  LightRequest_()
    : on(false)  {
    }
  LightRequest_(const ContainerAllocator& _alloc)
    : on(false)  {
  (void)_alloc;
    }



   typedef uint8_t _on_type;
  _on_type on;




  typedef boost::shared_ptr< ::sensor_actuator::LightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_actuator::LightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LightRequest_

typedef ::sensor_actuator::LightRequest_<std::allocator<void> > LightRequest;

typedef boost::shared_ptr< ::sensor_actuator::LightRequest > LightRequestPtr;
typedef boost::shared_ptr< ::sensor_actuator::LightRequest const> LightRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_actuator::LightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_actuator::LightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_actuator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_actuator': ['/home/kaiodt/kaio_ros_ws/devel/share/sensor_actuator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_actuator::LightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_actuator::LightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_actuator::LightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_actuator::LightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_actuator::LightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_actuator::LightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_actuator::LightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74983d2ffe4877de8ae30b7a94625c41";
  }

  static const char* value(const ::sensor_actuator::LightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74983d2ffe4877deULL;
  static const uint64_t static_value2 = 0x8ae30b7a94625c41ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_actuator::LightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_actuator/LightRequest";
  }

  static const char* value(const ::sensor_actuator::LightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_actuator::LightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool on\n\
";
  }

  static const char* value(const ::sensor_actuator::LightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_actuator::LightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_actuator::LightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_actuator::LightRequest_<ContainerAllocator>& v)
  {
    s << indent << "on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.on);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_ACTUATOR_MESSAGE_LIGHTREQUEST_H
