// Generated by gencpp from file sensor_actuator/LightResponse.msg
// DO NOT EDIT!


#ifndef SENSOR_ACTUATOR_MESSAGE_LIGHTRESPONSE_H
#define SENSOR_ACTUATOR_MESSAGE_LIGHTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_actuator
{
template <class ContainerAllocator>
struct LightResponse_
{
  typedef LightResponse_<ContainerAllocator> Type;

  LightResponse_()
    : status(false)  {
    }
  LightResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::sensor_actuator::LightResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_actuator::LightResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LightResponse_

typedef ::sensor_actuator::LightResponse_<std::allocator<void> > LightResponse;

typedef boost::shared_ptr< ::sensor_actuator::LightResponse > LightResponsePtr;
typedef boost::shared_ptr< ::sensor_actuator::LightResponse const> LightResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_actuator::LightResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_actuator::LightResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_actuator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_actuator': ['/home/kaiodt/kaio_ros_ws/devel/share/sensor_actuator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_actuator::LightResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_actuator::LightResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_actuator::LightResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_actuator::LightResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_actuator::LightResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_actuator::LightResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_actuator::LightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::sensor_actuator::LightResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_actuator::LightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_actuator/LightResponse";
  }

  static const char* value(const ::sensor_actuator::LightResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_actuator::LightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n\
\n\
";
  }

  static const char* value(const ::sensor_actuator::LightResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_actuator::LightResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_actuator::LightResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_actuator::LightResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_ACTUATOR_MESSAGE_LIGHTRESPONSE_H
