(cl:defpackage sensor_actuator-msg
  (:use )
  (:export
   "<ROTATIONACTIONRESULT>"
   "ROTATIONACTIONRESULT"
   "<ROTATIONACTIONFEEDBACK>"
   "ROTATIONACTIONFEEDBACK"
   "<ROTATIONFEEDBACK>"
   "ROTATIONFEEDBACK"
   "<ROTATIONACTIONGOAL>"
   "ROTATIONACTIONGOAL"
   "<ROTATIONGOAL>"
   "ROTATIONGOAL"
   "<ROTATIONRESULT>"
   "ROTATIONRESULT"
   "<ROTATIONACTION>"
   "ROTATIONACTION"
  ))

