; Auto-generated. Do not edit!


(cl:in-package sensor_actuator-msg)


;//! \htmlinclude RotationFeedback.msg.html

(cl:defclass <RotationFeedback> (roslisp-msg-protocol:ros-message)
  ((current_orientation
    :reader current_orientation
    :initarg :current_orientation
    :type cl:float
    :initform 0.0))
)

(cl:defclass RotationFeedback (<RotationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RotationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RotationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sensor_actuator-msg:<RotationFeedback> is deprecated: use sensor_actuator-msg:RotationFeedback instead.")))

(cl:ensure-generic-function 'current_orientation-val :lambda-list '(m))
(cl:defmethod current_orientation-val ((m <RotationFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sensor_actuator-msg:current_orientation-val is deprecated.  Use sensor_actuator-msg:current_orientation instead.")
  (current_orientation m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RotationFeedback>) ostream)
  "Serializes a message object of type '<RotationFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'current_orientation))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RotationFeedback>) istream)
  "Deserializes a message object of type '<RotationFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_orientation) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RotationFeedback>)))
  "Returns string type for a message object of type '<RotationFeedback>"
  "sensor_actuator/RotationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RotationFeedback)))
  "Returns string type for a message object of type 'RotationFeedback"
  "sensor_actuator/RotationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RotationFeedback>)))
  "Returns md5sum for a message object of type '<RotationFeedback>"
  "bd917ecfbe26055b91a2641b9ec145ff")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RotationFeedback)))
  "Returns md5sum for a message object of type 'RotationFeedback"
  "bd917ecfbe26055b91a2641b9ec145ff")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RotationFeedback>)))
  "Returns full string definition for message of type '<RotationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 current_orientation~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RotationFeedback)))
  "Returns full string definition for message of type 'RotationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 current_orientation~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RotationFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RotationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RotationFeedback
    (cl:cons ':current_orientation (current_orientation msg))
))
