; Auto-generated. Do not edit!


(cl:in-package sensor_actuator-msg)


;//! \htmlinclude RotationResult.msg.html

(cl:defclass <RotationResult> (roslisp-msg-protocol:ros-message)
  ((final_orientation
    :reader final_orientation
    :initarg :final_orientation
    :type cl:float
    :initform 0.0))
)

(cl:defclass RotationResult (<RotationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RotationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RotationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sensor_actuator-msg:<RotationResult> is deprecated: use sensor_actuator-msg:RotationResult instead.")))

(cl:ensure-generic-function 'final_orientation-val :lambda-list '(m))
(cl:defmethod final_orientation-val ((m <RotationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sensor_actuator-msg:final_orientation-val is deprecated.  Use sensor_actuator-msg:final_orientation instead.")
  (final_orientation m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RotationResult>) ostream)
  "Serializes a message object of type '<RotationResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'final_orientation))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RotationResult>) istream)
  "Deserializes a message object of type '<RotationResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'final_orientation) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RotationResult>)))
  "Returns string type for a message object of type '<RotationResult>"
  "sensor_actuator/RotationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RotationResult)))
  "Returns string type for a message object of type 'RotationResult"
  "sensor_actuator/RotationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RotationResult>)))
  "Returns md5sum for a message object of type '<RotationResult>"
  "b6fb98d1aa1e9e73903e30571f18e361")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RotationResult)))
  "Returns md5sum for a message object of type 'RotationResult"
  "b6fb98d1aa1e9e73903e30571f18e361")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RotationResult>)))
  "Returns full string definition for message of type '<RotationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 final_orientation~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RotationResult)))
  "Returns full string definition for message of type 'RotationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 final_orientation~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RotationResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RotationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'RotationResult
    (cl:cons ':final_orientation (final_orientation msg))
))
