; Auto-generated. Do not edit!


(cl:in-package sensor_actuator-msg)


;//! \htmlinclude RotationGoal.msg.html

(cl:defclass <RotationGoal> (roslisp-msg-protocol:ros-message)
  ((orientation
    :reader orientation
    :initarg :orientation
    :type cl:float
    :initform 0.0))
)

(cl:defclass RotationGoal (<RotationGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RotationGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RotationGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sensor_actuator-msg:<RotationGoal> is deprecated: use sensor_actuator-msg:RotationGoal instead.")))

(cl:ensure-generic-function 'orientation-val :lambda-list '(m))
(cl:defmethod orientation-val ((m <RotationGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sensor_actuator-msg:orientation-val is deprecated.  Use sensor_actuator-msg:orientation instead.")
  (orientation m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RotationGoal>) ostream)
  "Serializes a message object of type '<RotationGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'orientation))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RotationGoal>) istream)
  "Deserializes a message object of type '<RotationGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'orientation) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RotationGoal>)))
  "Returns string type for a message object of type '<RotationGoal>"
  "sensor_actuator/RotationGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RotationGoal)))
  "Returns string type for a message object of type 'RotationGoal"
  "sensor_actuator/RotationGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RotationGoal>)))
  "Returns md5sum for a message object of type '<RotationGoal>"
  "bb641cbf95db7d50ed249f4f84be9d83")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RotationGoal)))
  "Returns md5sum for a message object of type 'RotationGoal"
  "bb641cbf95db7d50ed249f4f84be9d83")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RotationGoal>)))
  "Returns full string definition for message of type '<RotationGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 orientation~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RotationGoal)))
  "Returns full string definition for message of type 'RotationGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 orientation~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RotationGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RotationGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RotationGoal
    (cl:cons ':orientation (orientation msg))
))
